travis:
  secure:
    BINSTAR_TOKEN: ZNB1vIcXWIOb849jr7zOvhtHb0NmRAl/h+r94KT99wP2VKDPNtICOn31W6RcTdL9eiUqREwyrI0OxOarTY1nAM+y8isFpdo5Z9wUntvaTeCwPecmmf2a3FmBZ9wEXWlVlrl6G//qJ8KFr9PAVJPYYcGP/cL1HHq3DleVo3LtwCQHY05/nvn0v+J3UgHG6y+g5qjDQU93/7KtOxyRPoB3zv7LH6Vk0GX+Vgh8dskxHkamyfMn+B5B8BK/lYNo7dv6P+Yrss2gwna4w3iCXvwwsYCLMFyJKOcqDJb0jOxQ9iA/Nnw5MZKpz1x3BlEEmpFACZIiSCVcEbPCT4MQPdlN+RNbofgPhDT9tXUAexhDvKhq87B9vjWnhlrMqB2XeJmk3YVynpghw2/duJlfCvVjiO5UjFKi80o8hVPefsZNl+5zZCUbsTQOZhJwEyVIqXjYxSmLqvVt3U3nWsFkTyeZ6x5vK3EZouw/w7NlasTSNwSmPDsM1xXXKBcSqHCBtlooJV1MYenhAm6DX0Mj1VMfxsBTpDSF6uNaoeKRzsTUFbqesiLMyIi+eBoZU4HHhnuJQwafaqlsgUrcAex0JDe46vfNMOQ3xeQZHR10flzkwl28oOn7c5QOlv0PvewCch27c4/ZKUUNdVI3qxXzCoePGCX4AG8sPSzbKpQO0SP5L30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
